### ISSUE TITLE
Indicate for each changeset listed whether it's still open

### ISSUE THREAD

**Issue by Hjart** [MichaelVL/osm-analytic-tracker#11]
Some mappers for various reasons do not close their changesets immediately after uploading (possible with Potlatch and JOSM). Changesets automatically close after about an hour of inactivity (last upload) and some mappers consistently leaves their changesets open until they automatically close. Changesets that have not yet closed can't be commented on and so when I want to comment on of those I have to wait until it has closed. Far from everyone knows this and currently the only way to check whether a changeset has closed is to open the changeset page and often the whole process is just a bit annoying. Would it be possible for each listed changeset to indicate whether it has closed?

**Comment by Hjart** [comment]
From to-nights list it looks like your analyzer might not quite be able to handle edits to objects created or modified by changesets which are still open.

**Comment by Hjart** [comment]
http://www.openstreetmap.org/changeset/37353201 was open more than 3 hours. I did some edits to it before it closed and the changeset in which I did this + my subsequent changesets still doesn't show up in the list even though other peoples changesets do. Appears that your code chokes on something here.

**Comment by michaelvl** [comment]
Added 'open' status to popup (it was easy since I deliberately removed it). I will keep an eye on the stability issue - I instrumented to code to debug the issue and if it happens again I should be able to fix it.

**Comment by Hjart** [comment]
Could you indicate 'open' status in the list instead, so I don't necessarily have to go hunt for the box on the map? In the popup both created_at and closed_at times are listed, so there it really doesn't make that much sense.
