### ISSUE TITLE
Is there a demo? 

### ISSUE THREAD

**Issue by panmona** [MichaelVL/osm-analytic-tracker#15]
Is there a demo of this software?

**Comment by Hjart** [comment]
There is a demo at https://osm.expandable.dk/ (which has been running for nearly 2 years now, covering all of the country Denmark)

**Comment by sfkeller** [comment]
Found that demo also in this nice blog post: https://www.openstreetmap.org/user/Cascafico/diary/42317. I've added OSMAT in the following OSM Wiki page. Feel free to open an own wiki page there: https://wiki.openstreetmap.org/wiki/Quality_assurance#OSMAT
