### ISSUE TITLE
Deleted addresses are not shown in the Address Changes tab

### ISSUE THREAD

**Issue by ghost** [MichaelVL/osm-analytic-tracker#17]
If a changeset deletes one or several address nodes (but does not edit or add any address nodes), the changeset will not be listed in the Address Changes tab (example: https://www.openstreetmap.org/changeset/60570613).
Similarly, if all address tags are removed from a node (but other tags still remain), this change will not show up on the Address Changes tag either (example: https://www.openstreetmap.org/changeset/60569970).
It would make manual validation of address edits easier if edits similar to the two above examples were listed on the Address Changes tab.

**Comment by michaelvl** [comment]
This is the FIXME in changeset.py:regex_test_changes().
