### ISSUE TITLE
Optimize API usage by using data from replication data

### ISSUE THREAD

**Issue by michaelvl** [MichaelVL/osm-analytic-tracker#22]

**Comment by michaelvl** [comment]
Each changeset triggers a metadata requests towards the API server to test the changeset bbox against the filtering area polygon. While the amount of data per changeset is small, the number of changesets are large, hence the traffic amount is considerable.

Since the replication data contains lat/lon of points, this data can be used instead to filter against.

This change should introduce a new filtering type that allows this type of 'is changeset with filtering area' test.

**Comment by michaelvl** [comment]
This is partly in commit daeafa33

**Comment by mmd-osm** [comment]
Maybe I'm missing something obvious here, but you would also be able to get changeset metadata from here: https://planet.openstreetmap.org/replication/changesets/ without querying the API.

**Comment by michaelvl** [comment]
Thanks, I will investigate if this is an even option.
