### ISSUE TITLE
Host machine freeze

### ISSUE THREAD

**Issue by cascafico** [MichaelVL/osm-analytic-tracker#23]
Host machine memory: 1Gbyte
In approx 5' running time ,memory left decrease to 90M, then host machine cannot be connected anymore. Left term sessions respond with I/O error only. System prune has been applied between tests.

pi@orangepipc:~$ docker system info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 35
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.11.12-sun8i
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 1
Total Memory: 971.4MiB
Name: orangepipc
ID: SAT5:NLV4:OULM:JPFZ:5PPY:N4TM:LLGW:64XX:777A:GKT3:VECF:K7O6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by michaelvl** [comment]
The docker-only version is not supported, running in low memory situations is also not guaranteed to work reliably.
