### ISSUE TITLE
sanitize input in diffmap.php?

### ISSUE THREAD

**Issue by poempelfox** [MichaelVL/osm-analytic-tracker#7]
I'm not much of a PHP programmer, but it would probably be wise to make sure $cid in diffmap.php only contains sane (integer) values before using it as part of a filename and echoing it back to the user.
Possibly something like

``` php
$cid = filter_input(INPUT_GET, 'cid', FILTER_SANITIZE_NUMBER_INT);
```

instead of

``` php
 $cid=$_GET['cid'];
```

?

**Comment by michaelvl** [comment]
Thanks for the feedback. This is now part of diffmap.php.
